export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGOUT = 'LOGOUT';

export const POPUP_DIALOG_FORGOTPASSWORD = 'POPUP_DIALOG_FORGOTPASSWORD';
export const POPUP_SPINNER = 'POPUP_SPINNER';
export const SET_SESSION_EXPIRED = 'SET_SESSION_EXPIRED';
export const UPDATE_ROLE_LIST = 'UPDATE_ROLE_LIST';

export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_USER_NAME_LIST = 'UPDATE_USERNAME_LIST';

export const SET_PERMISSON_LIST = 'SET_PERMISSON_LIST';
